"""add_pending_verification_status

Revision ID: 14c510e73d2c
Revises: 72e2045be2e4
Create Date: 2025-09-05 22:24:42.195394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c510e73d2c'
down_revision: Union[str, None] = '72e2045be2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pending_verification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_pending_verification')
    # ### end Alembic commands ###
