"""change category type to integer

Revision ID: 1f2aa26b86fd
Revises: 1c637d4fdc35
Create Date: 2025-06-25 23:43:49.086285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2aa26b86fd'
down_revision: Union[str, None] = '1c637d4fdc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 先将原有category字段重命名为category_old
    op.alter_column('items', 'category', new_column_name='category_old', existing_type=sa.String(length=50))
    # 2. 新增category字段为Integer类型
    op.add_column('items', sa.Column('category', sa.Integer(), nullable=True))
    # 3. 可选：如有需要，可在此处添加数据迁移逻辑（如字符串转数字）
    # 4. 删除category_old字段
    op.drop_column('items', 'category_old')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(length=50), nullable=True))
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
