"""add buy_request_id to messages

Revision ID: 202dc3076691
Revises: 750792150d71
Create Date: 2025-06-26 02:35:43.349725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '202dc3076691'
down_revision: Union[str, None] = '750792150d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'category',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('messages', sa.Column('buy_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'buy_requests', ['buy_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'buy_request_id')
    op.alter_column('items', 'category',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
