"""add images to buy_requests

Revision ID: 71f73dbb53c7
Revises: 2e4df9bf7de0
Create Date: 2025-06-27 23:17:38.018583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f73dbb53c7'
down_revision: Union[str, None] = '2e4df9bf7de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_requests', sa.Column('images', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_requests', 'images')
    # ### end Alembic commands ###
