"""Fix models and add necessary fields

Revision ID: 87f111a6245f
Revises: 4065c9aee756
Create Date: 2025-06-19 21:28:03.982715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f111a6245f'
down_revision: Union[str, None] = '4065c9aee756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('favorited_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('contact', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact')
    op.drop_column('items', 'favorited_count')
    op.drop_column('items', 'views')
    # ### end Alembic commands ###
