"""add_target_user_to_messages

Revision ID: 9dcc2d517ad2
Revises: c0c4cfca26e5
Create Date: 2025-06-28 22:07:30.648004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dcc2d517ad2'
down_revision: Union[str, None] = 'c0c4cfca26e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('target_user', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'target_user')
    # ### end Alembic commands ###
