"""add_item_sorting_tables

Revision ID: a08473bfd91a
Revises: 1164fca8824d
Create Date: 2025-09-11 14:23:38.820850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a08473bfd91a'
down_revision: Union[str, None] = '1164fca8824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sorting_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index(op.f('ix_sorting_configs_id'), 'sorting_configs', ['id'], unique=False)
    op.create_table('item_sorting_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('time_window_start', sa.DateTime(), nullable=False),
    sa.Column('time_window_end', sa.DateTime(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('favorites_count', sa.Integer(), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=True),
    sa.Column('seller_activity_score', sa.Float(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_sorting_metrics_id'), 'item_sorting_metrics', ['id'], unique=False)
    op.create_table('item_sorting_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('time_period', sa.String(length=20), nullable=False),
    sa.Column('base_weight', sa.Float(), nullable=True),
    sa.Column('trend_weight', sa.Float(), nullable=True),
    sa.Column('position_weight', sa.Float(), nullable=True),
    sa.Column('final_weight', sa.Float(), nullable=True),
    sa.Column('ranking_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_sorting_weights_id'), 'item_sorting_weights', ['id'], unique=False)
    op.alter_column('items', 'category',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'category',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_item_sorting_weights_id'), table_name='item_sorting_weights')
    op.drop_table('item_sorting_weights')
    op.drop_index(op.f('ix_item_sorting_metrics_id'), table_name='item_sorting_metrics')
    op.drop_table('item_sorting_metrics')
    op.drop_index(op.f('ix_sorting_configs_id'), table_name='sorting_configs')
    op.drop_table('sorting_configs')
    # ### end Alembic commands ###
