"""add_deleted_by_sender_and_receiver_to_message

Revision ID: b1d8239009fc
Revises: 71f73dbb53c7
Create Date: 2025-06-28 15:36:05.065797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d8239009fc'
down_revision: Union[str, None] = '71f73dbb53c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_by_receiver')
    op.drop_column('messages', 'deleted_by_sender')
    # ### end Alembic commands ###
