"""fix string length for mysql compatibility

Revision ID: c0c4cfca26e5
Revises: 25db883f4d6f
Create Date: 2025-06-28 21:34:13.858257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0c4cfca26e5'
down_revision: Union[str, None] = '25db883f4d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blocked_user_id', name='uq_user_blocked')
    )
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_user_friend')
    )
    op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=False)
    op.alter_column('buy_request_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('buy_request_likes', 'buy_request_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('buy_request_likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_buy_request_likes_id'), 'buy_request_likes', ['id'], unique=False)
    op.alter_column('buy_requests', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comment_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comment_likes', 'comment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comment_likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_comment_likes_id'), 'comment_likes', ['id'], unique=False)
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('item_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('item_likes', 'item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('item_likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_item_likes_id'), 'item_likes', ['id'], unique=False)
    op.alter_column('items', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_item_likes_id'), table_name='item_likes')
    op.alter_column('item_likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('item_likes', 'item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('item_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'content',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_comment_likes_id'), table_name='comment_likes')
    op.alter_column('comment_likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comment_likes', 'comment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comment_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('buy_requests', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_buy_request_likes_id'), table_name='buy_request_likes')
    op.alter_column('buy_request_likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('buy_request_likes', 'buy_request_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('buy_request_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_friends_id'), table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
